# yaml-language-server: $schema=../../../../../../packages/platform/schemas/lambda.schema.json
runtime: nodejs22.x
handler: index.handler
package: ../../../../../../apps/payment-api/dist/payment-api.zip
memoryMb: 128
timeoutSeconds: 10
logRetentionDays: 7
environment: {}

permissions:
  dynamodb:
    - service: customer-records
      actions:
        - dynamodb:PutItem
        - dynamodb:GetItem
